version: '3.4'
services:
  postgres:
    image: 'postgres:latest'
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lab6_spring_rest_api
    ports:
      - '5432:5432'
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'
    logging:
      options:
        max-size: 500k
        max-file: '10'
volumes:
  postgres_data:
    name: demo-postgres
